### ISSUE TITLE
Admin Tool Bar

### ISSUE THREAD

**Issue by Crittecol** [GuyPrimavera/aquila-admin-theme#12]
Hi, I love your admin theme! I just wanted to let you know it appears to have an incompatibility with the beaver builder theme that causes the admin bar to be invisible.

**Comment by GuyPrimavera** [comment]
Hi Crittecol,

Thanks a lot for letting me know! I'll soon be releasing an update so I'll investigate this issue before updating.

**Comment by GuyPrimavera** [comment]
Hi Crittecol,

I've just released a new version of this plugin with the admin bar "hidden" by default on the front-end, and replaced with a small icon to toggle it. This should fix your issue, but just let me know if you still find any issues.

Thanks.
