### ISSUE TITLE
Version 2.4.1

### ISSUE THREAD

**Issue by miscs** [GuyPrimavera/aquila-admin-theme#16]
Hi just checkin out the plugin - look very good!
Is the github version 2.4 and wordpress plugin directory version 2.4.1 the same? I cant see 2.4.1 here at github or am I missing something?

Thanks!

**Comment by GuyPrimavera** [comment]
Hey miscs,

Sorry for the late reply! I hadn't been keeping GitHub updated much before, but the project is now synced with GitHub so it should show the latest updates here from now onward.

Thanks.
